name: 'Progress Updater'
description: 'Get the development progress via a check message to see what the current progress of the project is.'
author: '0rangeFox'
inputs:
  path:
    required: true
    description: 'The directory to fetch the files'
    default: './src/'
  extension:
    required: true
    description: 'The valid extension for the verification'
    default: '.java'
  verification:
    required: true
    description: 'The verification message to see if the file is already developed'
    default: '// ### Progress-Updater ###'
outputs:
  totalFiles:
    description: 'Get amount of all files found on directory.'
  totalFilesWithExtension:
    description: 'Get amount of all files with the extension chosen found on directory.'
  totalFilesWithExtensionAndVerification:
    description: 'Get amount of all files with the extension and verification chosen found on directory.'
  progress:
    description: 'Get the progress with precision.'
  progressRounded:
    description: 'Get the progress rounded with 2 decimals.'
  progressInteger:
    description: 'Get the progress without decimals.'
runs:
  using: 'node12'
  main: 'dist/index.js'
